#!/usr/bin/sh

# *.out: ACELP bits stream file

# cdecoder (Channel Decoder):
# The cdecoder processes the raw data stream extracted directly from the radio air interface.
# Primary Function: It performs forward error correction (FEC) and detects bad frames.
# Input: Reassembled, demodulated bits received from the physical layer over the air interface.
# Key Tasks: 	De-interleaving: Reorders bits that were scrambled over multiple time slots to minimize the impact of burst errors.
# 		Convolutional Decoding: Uses algorithms (like Viterbi) to fix bit errors caused by atmospheric interference or long distances.
# 		CRC Checks: Identifies if a packet is too corrupted to save.
# Output: A clean, compressed digital voice stream (typically 4.56 kbps) passed directly to the next stage.

# sdecoder (Speech Decoder):
# The sdecoder performs the digital-to-analog translation of the vocal data.
# Primary Function: It decompresses the clean voice frames into raw, uncompressed audio.
# Input: The error-corrected, compressed bitstream generated by the cdecoder.
# Key Tasks:CELP Synthesis: TETRA uses Algebraic Code-Excited Linear Prediction (ACELP).
# The sdecoder takes the matrix codebook indexes from the bitstream and maps them to synthesize human vocal properties.
# Audio Reconstruction: Translates parameters like pitch, volume, and vocal formants back into linear Pulse-Code Modulation (PCM) audio.
# Output: Raw audio samples (typically 8 kHz, 16-bit PCM Mono) which can be written directly to a .wav file or sent to a computer speaker.

# aplay         : audio player
# S16_LE        : Signed 16 bit Little Endian
# r 8000        : rate 8000 Hz
# c 1           : Mono

cat ~/Downloads/out/*.out | cdecoder /dev/stdin /dev/stdout | sdecoder /dev/stdin /dev/stdout | aplay -f S16_LE -r 8000 -c 1
