%TAG ! tag:actinid.org,2022:suscan:
---
- !source_config
  type: file
  format: WAV
  label: FT8
  path: /home/mkhuthir/rfdata/FT8/SDRuno_20200904_135545Z_7076kHz.wav
  antenna: RX
  freq: 7076000.0000000000000000
  lnb_freq: 0.0000000000000000
  bandwidth: 1000000.00000000
  iq_balance: false
  dc_remove: true
  ppm: 12.00000000
  start_time: 1599227745.000000
  loop: true
  samp_rate: 62500
  average: 1
  channel: 0
  device:
    uri: local://soapysdr/
    params: {}
  gains: {}
