%TAG ! tag:actinid.org,2022:suscan:
---
- !qtui
  version: 1
  width: 1870
  height: 1011
  x: 50
  y: 69
  fullScreen: false
  sidePanelRatio: 2.320471596998928132e-01
  disableHighRateWarning: false
  disableConnectionQualityWarning: false
  loFreq: -10828
  bandwidth: 2083
  lastLoadedFile:
  mainWindowState: AAAA/wAAAAD9AAAAAAAAB04AAANqAAAABAAAAAQAAAAIAAAACPwAAAACAAAAAgAAAAQAAAAWAG0AYQBpAG4AVABvAG8AbABCAGEAcgEAAAAA/////wAAAAAAAAAAAAAALgBJAG4AcwBwAFQAbwBvAGwAVwBpAGQAZwBlAHQAOgA6AEEAYwB0AGkAbwBuAHMBAAAAkv////8AAAAAAAAAAAAAACgAQQB1AGQAaQBvAFcAaQBkAGcAZQB0ADoAOgBBAGMAdABpAG8AbgBzAQAAASb/////AAAAAAAAAAAAAAAWAGgAZQBsAHAAVABvAG8AbABCAGEAcgEAAAH8/////wAAAAAAAAAAAAAAAgAAAAIAAAAgAFMAbwB1AHIAYwBlAFQAaQBtAGUAVwBpAGQAZwBlAHQAAAAAAP////8AAAAAAAAAAAAAACIAVABpAG0AZQBTAGwAaQBkAGUAcgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA=
  source: !source_config
    type: file
    format: WAV
    label: My FT8
    path: /home/mkhuthir/rfdata/FT8/SDRuno_20200904_135545Z_7076kHz.wav
    antenna: RX
    freq: 7075076.0000000000000000
    lnb_freq: 0.0000000000000000
    bandwidth: 62500.00000000
    iq_balance: false
    dc_remove: true
    ppm: 12.00000000
    start_time: 1599227745.000000
    loop: true
    samp_rate: 62500
    average: 1
    channel: 0
    device:
      uri: local://soapysdr/
      params: {}
    gains: {}
  analyzerParams: !AnalyzerParams
    channelUpdateInterval: 0.10000000
    psdUpdateInterval: 0.02000000
    spectrumAvgAlpha: 0.01000000
    sAvgAlpha: 0.00100000
    nAvgAlpha: 0.50000000
    snr: 2.00000000
    windowSize: 8192
    minFreq: 0.000000000000000000e+00
    maxFreq: 0.000000000000000000e+00
    windowFunction: blackmann-harris
    mode: channel
  colors: !colorcfg
    lcdBackground: '#070d0c'
    lcdForeground: '#00ff00'
    spectrumBackground: '#070d0c'
    spectrumForeground: '#00ff00'
    spectrumAxes: '#005b88'
    spectrumText: '#ffffff'
    constellationForeground: '#3ed180'
    constellationBackground: '#070d0c'
    constellationAxes: '#152d2b'
    transitionForeground: '#3ed180'
    transitionBackground: '#070d0c'
    transitionAxes: '#152d2b'
    histogramForeground: '#3ed180'
    histogramBackground: '#070d0c'
    histogramAxes: '#152d2b'
    histogramModel: '#ffff00'
    symViewLow: '#000000'
    symViewHigh: '#ffffff'
    symViewBackground: '#134529'
    selection: '#384c1a'
    filterBox: '#49b67a'
  audio: !AudioConfig
    devStr:
    description:
  remoteCtl: !RemoteControlConfig
    host: localhost
    port: 1234
    enabled: false
  guiConfig: !guicfg
    useLMBdrag: false
    noLimits: false
    useGLWaterfall: true
    useMaxBlending: false
    useGlInWindows: true
    enableMsgTTL: true
    msgTTL: 15
    infoText:
    infoTextColor: '#3e80d1'
  tleSourceConfig: !tlesrccfg
    autoDownloadOnStartup: false
  panoramicSpectrum: !PanoramicDialogConfig
    fullRange: true
    rangeMin: 0.000000000000000000e+00
    rangeMax: 6.000000000000000000e+09
    panRangeMin: -90.00000000
    panRangeMax: 0.00000000
    lnbFreq: 0.000000000000000000e+00
    device: Audio input (default)
    antenna:
    sampRate: 20000000
    strategy: Stochastic
    partitioning: Continuous
    palette: Turbo (Gqrx)
  bandPlans: []
  Components:
    AudioWidget: !AudioWidgetConfig
      enabled: true
      collapsed: false
      lockToFreq: false
      agc: fast
      demod: USB
      rate: 44100
      cutOff: 22050.00000000
      volume: -12.00000000
      savePath:
      squelch: false
      amSquelch: 0.00000000
      ssbSquelch: 0.00100000
      tleCorrection: false
      isSatellite: false
      satName:
      tleData:
    SourceWidget: !SourceWidgetConfig
      collapsed: true
      throttle: false
      throttleRate: 196000
      dcRemove: true
      iqRev: false
      agcEnabled: false
      gainPresetEnabled: false
      allocHistory: false
      replayAllocationMiB: 1.000000000000000000e+02
      dataSaverConfig: !DataSaverConfig
        path: /home/mkhuthir/Downloads
      savedPresets: []
    InspToolWidget: !InspToolWidgetConfig
      collapsed: true
      inspectorClass: audio
      inspFactory: GenericInspectorFactory
      precise: false
      palette: Suscan
      paletteOffset: 0
      paletteContrast: 0
      autoSquelchTriggerSNR: 10.00000000
    FFTWidget: !FFTWidgetConfig
      collapsed: true
      averaging: 0.45400000
      panWfRatio: 0.50000000
      peakDetect: false
      peakHold: false
      filled: true
      panRangeMin: -68.00000000
      panRangeMax: 3.00000000
      wfRangeMin: -68.00000000
      wfRangeMax: 3.00000000
      palette: Gqrx
      zoom: 1.00000000
      rangeLock: true
      channels: true
      timeSpan: 0
      timeStamps: false
      utcTimeStamps: true
      bookmarks: true
      unitName: dBFS
      zeroPoint: 0.00000000
      gain: 50.00000000
      clickResolution: 1
    SourceTimeWidget: !SourceTimeWidget
      visible: false
    GenericInspectorFactory: !GenericInspectorConfig
      spectrumPalette: Inferno (Feely)
      spectrumRatio: 0.28999999
      waveFormPalette: Inferno (Feely)
      waveFormOffset: 0
      waveFormContrast: 1
      peakHold: false
      peakDetect: false
      units: dBFS
      gain: 0.00000000
      zeroPoint: 0.00000000
    RMSInspectorFactory: !RMSInspectorConfig
      integrate: 1
      integrationTime: 0.02000000
      dBscale: true
      autoFit: true
      timeAxisType: 0
      autoScroll: true
      currScaleMin: -48.00000000
      currScaleMax: 0.00000000
      logData: false
      logDir:
      logFormat: csv
      host: 127.0.0.1
      port: 9999
